### PR TITLE
Updated SwiftyJSON, difficulty retrieving in the Article class, some refactoring and added documentation for all public properties/methods/classes

### PR DESCRIPTION
**Pull request by JorritO**

### CODE REVIEW

**Comment by mircealungu** [comment]
I like the documentation generator script. Can we run it automatically on the build server? That would be cool :)

**Comment by JorritO** [comment]
What would be the point of that? It would only create it locally and after the build is finished, it is gone. To make it useful, it should be uploaded to a web server, or something like that.

Met vriendelijke groet,
Jorrit Oosterhof

**Comment by mircealungu** [comment]
Evidently it should be updated to a server :)

**Comment by mircealungu** [comment]
Although if you push it to github then it's on a server... :)

**Comment by JorritO** [comment]
I think it would be nicer to just upload it to a server then, because that makes it a bit nicer, or does GitHub support viewing HTML files as if it was a regular website?

Met vriendelijke groet,
Jorrit Oosterhof

> Op 2 mei 2016, om 20:05 heeft Mircea Filip Lungu notifications@github.com het volgende geschreven:
> 
> Although if you push it to github then it's on a server... :)
>

**Comment by mircealungu** [comment]
https://pages.github.com/ is the github hosting solution.

M.

**Pull request merged**
